export const action= {
    INCREMENT: "INCREMENT",
    DECREMENT: "DECREMENT",
    ADD_TODO: "ADD_TODO",
    TOGGLE_TODO: "TOGGLE_TODO",
    REMOVE_TODO: "REMOVE_TODO",
    SET_VISIBILITY_FILTER: "SET_VISIBILITY_FILTER"
};